1\. Write the following as a list comprehension

In [1]:
# 1
ans = []
for i in range(3):
    for j in range(4):
        ans.append((i, j))
print (ans)

# 2
ans = map(lambda x: x*x, filter(lambda x: x%2 == 0, range(5)))
print (list(ans))



[(0, 0), (0, 1), (0, 2), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3)]
[0, 4, 16]


In [2]:
my_list = [(i, j) for i in range(3) for j in range(4)]
print(my_list)

[(0, 0), (0, 1), (0, 2), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3)]


In [3]:
my_list = [i*i for i in range(5) if i%2 == 0]
print(my_list)

[0, 4, 16]


2\. Convert the following function into a pure function with no global variables or side effects

In [4]:
x = 5
def f(alist):
    for i in range(x):
         alist.append(i)
    return alist

alist = [1,2,3]
ans = f(alist)
print (ans)
print (alist) # alist has been changed!

[1, 2, 3, 0, 1, 2, 3, 4]
[1, 2, 3, 0, 1, 2, 3, 4]


In [5]:
def f(mylist):
    x = 5
    mylist2 = mylist.copy()
    for i in range(x):
         mylist2.append(i)
    return list(mylist2)

alist = [1,2,3]
ans = f(alist)
print (ans)
print (alist)

[1, 2, 3, 0, 1, 2, 3, 4]
[1, 2, 3]


3\. Write a `decorator` hello that makes every wrapped function print “Hello!”, i.e. something like:

```python
@hello
def square(x):
    return x*x
```



In [1]:
def hello(func):
    def wrapper(*args, **kargs):
        print("Hello")
        return(func(*args, **kargs))
    return(wrapper)

@hello
def square(x):
    return x*x

print(square(2))

Hello
4


4\. Write the factorial function so that it a) does and b) does not use recursion.

In [15]:
# With recursion
try:
    number = int(input("What number you wanna compute the factorial of? "))
    def factorial(n):
        if n == 0:
            return 1
        else:
            return factorial(n-1)*n

    
    print(f"The factorial of {number} is {factorial(number)}")
except ValueError:
    print("You must type a number")

What number you wanna compute the factorial of? 5
The factorial of 5 is 120


In [2]:
number = int(input("What is the number to compute the factorial on? "))
def factorial(n):
    if n == 0:
        return 1
    else:
        my_factorial = 1
        for i in range(n):
            my_factorial *= (i+1)
    return(my_factorial)


print(f"The factorial of {number} is {factorial(number)}")

What is the number to compute the factorial on? 5
The factorial of 5 is 120


In [3]:
try:
    number = int(input("What is the number to compute the factorial on? "))
    def factorial(n):
        if n == 0:
            return 1
        else:
            my_factorial = 1
            for i in range(n):
                my_factorial *= (i+1)
        return(my_factorial)


    print(f"The factorial of {number} is {factorial(number)}")
except ValueError:
    print("You must type an integer number")

What is the number to compute the factorial on? 5
The factorial of 5 is 120


5\. Use HOFs (zip in particular) to compute the weight of a circle, a disk and a sphere, assuming different radii and different densities:

```python
densities = {"Al":[0.5,1,2],"Fe":[3,4,5],"Pb": [15,20,30]}
radii = [1,2,3]
```

where the entries of the dictionary's values are the linear, superficial and volumetric densities of the materials respectively.

In particular define a list of three lambda functions using a comprehension that computes the circumference, the area and the volume for a given radius.


In [6]:
import math
import numpy as np


densities = {"Al":[0.5,1,2],"Fe":[3,4,5],"Pb": [15,20,30]}
radii = [1,2,3]
circle_weight = lambda linear_density, radius: (2*math.pi*radius)*linear_density
disk_weight = lambda superficial_density, radius: (math.pi*radius**2)*superficial_density
sphere_weight = lambda volumetric_density, radius: (4/3)*math.pi*(radius**3)*volumetric_density
my_densities = [[x, y, z] for x, y, z in zip(densities["Al"], densities["Fe"], densities["Pb"])]
weights = []
# Every column is a different material, each row represent, respectively, 
#the weight of the circle, disk and sphere,
# every block is a different radius
for r in radii:
    weights.append([[circle_weight(x, r) for x in my_densities[0]], [disk_weight(x, r) for x in my_densities[1]], [sphere_weight(x, r) for x in my_densities[2]]])
print("""Every column is, respectively, aluminium, iron and lead 
each row represent, respectively, the weight of the circle, disk and sphere,
every block is, respectively: radius = 1, 2, 3.\n""")
print(np.array(weights))

Every column is, respectively, aluminium, iron and lead 
each row represent, respectively, the weight of the circle, disk and sphere,
every block is, respectively: radius = 1, 2, 3.

[[[3.14159265e+00 1.88495559e+01 9.42477796e+01]
  [3.14159265e+00 1.25663706e+01 6.28318531e+01]
  [8.37758041e+00 2.09439510e+01 1.25663706e+02]]

 [[6.28318531e+00 3.76991118e+01 1.88495559e+02]
  [1.25663706e+01 5.02654825e+01 2.51327412e+02]
  [6.70206433e+01 1.67551608e+02 1.00530965e+03]]

 [[9.42477796e+00 5.65486678e+01 2.82743339e+02]
  [2.82743339e+01 1.13097336e+02 5.65486678e+02]
  [2.26194671e+02 5.65486678e+02 3.39292007e+03]]]


6\. Edit the class defintion to add an instance attribute of is_hungry = True to the Dog class. Then add a method called eat() which changes the value of is_hungry to False when called. Figure out the best way to feed each dog and then output “My dogs are hungry.” if all are hungry or “My dogs are not hungry.” if all are not hungry. The final output should look like this:

`I have 3 dogs. 
Tom is 6. 
Fletcher is 7. 
Larry is 9. 
And they're all mammals, of course. 
My dogs are not hungry.
`

```python
# Parent class
class Dog:

    # Class attribute
    species = 'mammal'

    # Initializer / Instance attributes
    def __init__(self, name, age):
        self.name = name
        self.age = age

    # instance method
    def description(self):
        return "{} is {} years old".format(self.name, self.age)

    # instance method
    def speak(self, sound):
        return "{} says {}".format(self.name, sound)

# Child class (inherits from Dog class)
class RussellTerrier(Dog):
    def run(self, speed):
        return "{} runs {}".format(self.name, speed)

# Child class (inherits from Dog class)
class Bulldog(Dog):
    def run(self, speed):
        return "{} runs {}".format(self.name, speed)
```

In [7]:
import sys
class Dog:
    # Class attribute
    species = 'mammal'

    # Initializer / Instance attributes
    def __init__(self, name, age, is_hungry):
        self.name = name
        self.age = age
        self.is_hungry = is_hungry

    # instance method
    def description(self):
        return "{} is {} years old".format(self.name, self.age)

    def eat(self, is_hungry = True):
        dog_fed = input(f"Do you wanna feed {self.name}?[y, n] ")
        if dog_fed.lower() == "y":
            self.is_hungry = False
        elif dog_fed.lower() == "n":
            pass
        else:
            sys.exit("You must type either \"y\" or \"n\"")

            # instance method


    def speak(self, sound):
        return "{} says {}".format(self.name, sound)


# Child class (inherits from Dog class)
class RussellTerrier(Dog):
    def run(self, speed):
        return "{} runs {}".format(self.name, speed)


# Child class (inherits from Dog class)
class Bulldog(Dog):
    def run(self, speed):
        return "{} runs {}".format(self.name, speed)


first_dog = Dog("Tom", 6, True)
second_dog = Dog("Fletcher", 7, True)
third_dog = Dog("Larry", 9, True)
first_dog.eat()
second_dog.eat()
third_dog.eat()
print(f"""I have 3 dogs,
{first_dog.name} is {first_dog.age}
{second_dog.name} is {second_dog.age}
{third_dog.name} is {third_dog.age}
and they are all {Dog.species}s of course.""")
if not first_dog.is_hungry and not second_dog.is_hungry and not third_dog.is_hungry:
    print("My dogs are not hungry")
else:
    print("My dogs are hungry")

Do you wanna feed Tom?[y, n] y
Do you wanna feed Fletcher?[y, n] y
Do you wanna feed Larry?[y, n] 5


SystemExit: You must type either "y" or "n"